development:
  adapter: mysql2
  encoding: utf8
  database: template_dev
  username: root
  password: ''

test: &test
  adapter: mysql2
  encoding: utf8
  database: template_test
  username: root
  password: ''

production:
  adapter: mysql2
  encoding: utf8
  database: template_prod
  username: root
  password: ''

cucumber:
  <<: *test
